name: Nix

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check:
          - formatting
          - go-bindings
          - haskell-bindings
          - reprolang
          - reprolang-generated
          - rust-bindings
          - typescript-bindings
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix build .#checks.x86_64-linux.${{ matrix.check }}

  runs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - scip
          - proto-generate
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix run .#${{ matrix.package }}
      - run: git diff --exit-code
