name: Nix

on:
  pull_request:

jobs:
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix fmt -- --check .

  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check:
          - go-bindings
          - haskell-bindings
          - prettier
          - reprolang
          - reprolang-generated
          - rust-bindings
          - typescript-bindings
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix build .#checks.x86_64-linux.${{ matrix.check }}
